disabled_rules:
  - line_length

included: # paths to include during linting. `--path` is ignored if present.
  - YourService
  - Ext

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Gen
  - Pods

line_length: 80
variable_name_min_length: 2

